export const slashCommands = [
  "/instance list",
  "/instance create",
  "/instance show",
  "/instance delete",
  "/instance restart",
  "/ask",
  "/llm configure",
  "/llm test",
  "/llm show",
  "/flavor list",
  "/flavor pick",
  "/backup create",
  "/backup list",
  "/diagnose",
  "/chat",
  "/configure",
  "/connect",
  "/status",
  "/help",
  "/clear",
  "/exit",
];